version: "3.8"

services:
  tamilrockerstorrentcleanup:
    build: .
    container_name: tamilrockerstorrentcleanup
    restart: no
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      QBITIP: ${QBITIP}
      QBITUSER: ${QBITUSER}
      QBITPASS: ${QBITPASS}
      HA_WEBHOOK_URL: ${HA_WEBHOOK_URL} 
      #webhook url for triggering next app after finishing this tasks
   






